version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - yamdb_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    image: yurydenorth/sprint16_p:1
    # build: ./api_yamdb
    # build: ../api_yamdb
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      - static_value:/var/html/static/

      - media_value:/var/html/media/

    depends_on:
      - web

volumes:
  yamdb_data:
  static_value:
  media_value:
